{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-reload-demo.fullname" . }}
  labels:
    {{- include "config-reload-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  API_KEY: {{ .Values.secrets.apiKey | quote }}
{{- end }}
